var numTable = prompt('Enter a Number of Table')
document.write('<h1>Table of : ', numTable , '</h1>')
var value = parseInt(numTable)
document.write(value ,' * 1 = ',value * 1 ,'<br>')
document.write(value ,' * 2 = ',value * 2 ,'<br>')
document.write(value ,' * 3 = ',value * 3 ,'<br>')
document.write(value ,' * 4 = ',value * 4 ,'<br>')
document.write(value ,' * 5 = ',value * 5 ,'<br>')
document.write(value ,' * 6 = ',value * 6 ,'<br>')
document.write(value ,' * 7 = ',value * 7 ,'<br>')
document.write(value ,' * 8 = ',value * 8 ,'<br>')
document.write(value ,' * 9 = ',value * 9 ,'<br>')
document.write(value ,' * 10 = ',value * 10)